In [ ]:
# 필요 라이브러리 불러오기
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from glob import glob

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
raw_path = '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/'
report_lst = glob(f'{raw_path}20*.csv')

pd.read_csv(report_lst[-1]).sort_values(['cluster', 'z_total'], ascending=False)#[['category','cluster', 'z_total']]

,category,cluster,orders,price,sellers,price_mean,order_mean,price_std,order_std,z_price_mean,z_order_mean,z_price_std,z_order_std,z_total,z_order,z_price
5,bed_bath_table,S,775,74473.66,79,942.70,9.81,1588861.72,140.06,0.203107,1.196113,0.078349,-0.467295,1.01,0.73,0.28
6,computers_accessories,S,551,60395.38,81,745.62,6.80,777069.95,47.62,-0.122997,0.232529,0.336107,0.354206,0.80,0.59,0.21
8,health_beauty,S,704,92590.45,141,656.67,4.99,831762.67,33.34,-0.270180,-0.346902,0.318741,0.481110,0.18,0.13,0.05
9,sports_leisure,S,612,68530.74,147,466.20,4.16,210910.00,12.49,-0.585346,-0.612608,0.515873,0.666401,-0.02,0.05,-0.07
10,watches_gifts,S,532,100471.04,39,2576.18,13.64,11141875.33,385.63,2.905988,2.422201,-2.954905,-2.649638,-0.28,-0.23,-0.05
7,furniture_decor,S,630,60707.11,94,645.82,6.70,1272308.93,135.75,-0.288133,0.200516,0.178860,-0.428992,-0.34,-0.23,-0.11
0,auto,A,366,50370.20,98,513.98,3.73,253762.74,15.27,-0.506286,-0.750263,0.502267,0.641695,-0.11,-0.11,-0.00
2,cool_stuff,A,211,36048.30,52,693.24,4.06,1025626.70,32.24,-0.209669,-0.644620,0.257186,0.490885,-0.11,-0.15,0.05
1,baby,A,250,50411.03,64,787.67,3.91,2228230.16,12.26,-0.053417,-0.692640,-0.124662,0.668445,-0.20,-0.02,-0.18
4,housewares,A,493,46824.45,135,346.85,3.65,133842.82,9.80,-0.782832,-0.775873,0.540343,0.690306,-0.33,-0.09,-0.24
3,garden_tools,A,300,36095.07,56,644.55,5.36,727518.23,137.79,-0.290235,-0.228455,0.351841,-0.447122,-0.61,-0.68,0.06

In [ ]:
report_lst

['/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2016-10.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2017-06.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2017-02.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2017-08.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2017-03.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2017-01.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2017-10.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2017-07.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2017-09.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2017-05.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2017-04.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2017-11.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2017-12.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2018-07.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2018-06.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2018-02.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2018-03.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2018-01.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2018-05.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2018-08.csv',
 '/content/drive/MyDrive/Colab Notebooks/프로젝트/datathon/data/2018-04.csv']

In [ ]:
df_1610 = pd.read_csv(report_lst[0])
df_1701 = pd.read_csv(report_lst[1])
df_1702 = pd.read_csv(report_lst[2])
df_1703 = pd.read_csv(report_lst[3])
df_1704 = pd.read_csv(report_lst[4])
df_1705 = pd.read_csv(report_lst[5])
df_1706 = pd.read_csv(report_lst[6])
df_1707 = pd.read_csv(report_lst[7])
df_1708 = pd.read_csv(report_lst[8])
df_1709 = pd.read_csv(report_lst[9])
df_1710 = pd.read_csv(report_lst[10])
df_1711 = pd.read_csv(report_lst[11])
df_1712 = pd.read_csv(report_lst[12])
df_1801 = pd.read_csv(report_lst[13])
df_1802 = pd.read_csv(report_lst[14])
df_1803 = pd.read_csv(report_lst[15])
df_1804 = pd.read_csv(report_lst[16])
df_1805 = pd.read_csv(report_lst[17])
df_1806 = pd.read_csv(report_lst[18])
df_1807 = pd.read_csv(report_lst[19])
df_1808 = pd.read_csv(report_lst[20])

In [ ]:
report_df_lst = [df_1610, 
df_1701,
df_1702,
df_1703,
df_1704,
df_1705,
df_1706,
df_1707,
df_1708,
df_1709,
df_1710,
df_1711,
df_1712,
df_1801,
df_1802,
df_1803,
df_1804,
df_1805,
df_1806,
df_1807,
df_1808]

In [ ]:
ym = ['2016-10',
'2017-06',
'2017-02',
'2017-08',
'2017-03',
'2017-01',
'2017-10',
'2017-07',
'2017-09',
'2017-05',
'2017-04',
'2017-11',
'2017-12',
'2018-07',
'2018-06',
'2018-02',
'2018-03',
'2018-01',
'2018-05',
'2018-08',
'2018-04']

In [ ]:
category_lst = []
for i in report_df_lst:
    category_lst.append(i['category'].tolist())

In [ ]:
category_dict = dict(zip(ym, category_lst))
category_dict['2018-01']

['cool_stuff',
 'housewares',
 'stationery',
 'watches_gifts',
 'bed_bath_table',
 'computers_accessories',
 'furniture_decor',
 'health_beauty',
 'sports_leisure']

In [ ]:
for key, val in category_dict.items():
    display(pd.DataFrame({key:val}))
    break

           2016-10
0    health_beauty
1        perfumery
2             toys
3  furniture_decor

In [ ]:
ym[9] == '2017-05'

True

In [ ]:
category_dict['2017-05']

['auto',
 'garden_tools',
 'musical_instruments',
 'perfumery',
 'toys',
 'watches_gifts',
 'bed_bath_table',
 'computers_accessories',
 'cool_stuff',
 'furniture_decor',
 'health_beauty',
 'housewares',
 'sports_leisure']

In [ ]:
report_df_lst[0]['cluster'].values

array(['A', 'A', 'A', 'S'], dtype=object)

In [ ]:
lst = []
for x, y in zip(ym, report_df_lst):
    lst.append(pd.DataFrame({x:y['cluster'].values}, index=y['category']).T)

In [ ]:
category_SA = pd.concat(lst, axis=0).fillna(0).sort_index()
category_SA

category,health_beauty,perfumery,toys,furniture_decor,auto,garden_tools,telephony,watches_gifts,bed_bath_table,computers_accessories,cool_stuff,housewares,sports_leisure,office_furniture,baby,musical_instruments,small_appliances,stationery
2016-10,A,A,A,S,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2017-01,A,0,0,S,0,A,0,0,0,0,0,0,A,0,0,0,0,0
2017-02,S,A,A,S,A,A,A,A,S,A,A,A,S,A,0,0,0,0
2017-03,A,A,0,S,0,A,0,A,S,A,A,A,A,0,0,0,0,0
2017-04,S,A,0,S,A,A,0,A,S,A,A,0,S,0,0,0,A,0
2017-05,S,A,A,S,A,A,0,A,S,S,S,S,S,0,0,A,0,0
2017-06,S,A,A,A,A,A,A,A,S,S,S,S,S,0,0,0,0,0
2017-07,A,0,A,A,0,0,0,A,S,A,A,A,A,0,0,0,0,0
2017-08,S,0,0,S,0,A,0,A,S,A,A,A,S,0,0,0,0,0
2017-09,S,A,A,A,0,A,A,A,S,A,A,A,S,0,A,0,0,0
2017-10,A,0,A,A,0,A,0,S,S,A,A,0,S,0,0,0,0,0
2017-11,A,0,A,S,0,0,0,A,S,A,0,0,A,0,0,0,0,0
2017-12,S,A,S,A,A,A,0,S,S,A,A,A,S,0,0,0,0,A
2018-01,S,0,0,S,0,0,0,A,S,S,A,A,S,0,0,0,0,A
2018-02,S,0,0,A,A,0,0,A,S,S,0,A,S,0,0,0,0,0
2018-03,S,0,0,S,0,0,0,A,S,S,0,0,S,0,0,0,0,0
2018-04,S,0,0,S,A,A,0,S,S,S,A,A,S,0,A,0,0,0
2018-05,S,0,0,A,0,0,0,S,A,A,0,A,A,0,0,0,0,0
2018-06,S,0,0,A,A,0,0,S,S,A,0,A,A,0,0,0,0,0
2018-07,S,0,0,A,A,0,0,S,A,A,0,A,A,0,0,0,0,0
2018-08,S,0,0,A,A,0,0,A,A,A,0,A,A,0,0,0,0,0

In [ ]:
category_21 = category_SA.replace('S', 2)
category_21 = category_21.replace('A', 1)
category_21

category,health_beauty,perfumery,toys,furniture_decor,auto,garden_tools,telephony,watches_gifts,bed_bath_table,computers_accessories,cool_stuff,housewares,sports_leisure,office_furniture,baby,musical_instruments,small_appliances,stationery
2016-10,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2017-01,1,0,0,2,0,1,0,0,0,0,0,0,1,0,0,0,0,0
2017-02,2,1,1,2,1,1,1,1,2,1,1,1,2,1,0,0,0,0
2017-03,1,1,0,2,0,1,0,1,2,1,1,1,1,0,0,0,0,0
2017-04,2,1,0,2,1,1,0,1,2,1,1,0,2,0,0,0,1,0
2017-05,2,1,1,2,1,1,0,1,2,2,2,2,2,0,0,1,0,0
2017-06,2,1,1,1,1,1,1,1,2,2,2,2,2,0,0,0,0,0
2017-07,1,0,1,1,0,0,0,1,2,1,1,1,1,0,0,0,0,0
2017-08,2,0,0,2,0,1,0,1,2,1,1,1,2,0,0,0,0,0
2017-09,2,1,1,1,0,1,1,1,2,1,1,1,2,0,1,0,0,0
2017-10,1,0,1,1,0,1,0,2,2,1,1,0,2,0,0,0,0,0
2017-11,1,0,1,2,0,0,0,1,2,1,0,0,1,0,0,0,0,0
2017-12,2,1,2,1,1,1,0,2,2,1,1,1,2,0,0,0,0,1
2018-01,2,0,0,2,0,0,0,1,2,2,1,1,2,0,0,0,0,1
2018-02,2,0,0,1,1,0,0,1,2,2,0,1,2,0,0,0,0,0
2018-03,2,0,0,2,0,0,0,1,2,2,0,0,2,0,0,0,0,0
2018-04,2,0,0,2,1,1,0,2,2,2,1,1,2,0,1,0,0,0
2018-05,2,0,0,1,0,0,0,2,1,1,0,1,1,0,0,0,0,0
2018-06,2,0,0,1,1,0,0,2,2,1,0,1,1,0,0,0,0,0
2018-07,2,0,0,1,1,0,0,2,1,1,0,1,1,0,0,0,0,0
2018-08,2,0,0,1,1,0,0,1,1,1,0,1,1,0,0,0,0,0

In [ ]:
category_21.sum()

category
health_beauty            36
perfumery                 8
toys                     10
furniture_decor          32
auto                     10
garden_tools             11
telephony                 3
watches_gifts            25
bed_bath_table           35
computers_accessories    25
cool_stuff               14
housewares               17
sports_leisure           32
office_furniture          1
baby                      2
musical_instruments       1
small_appliances          1
stationery                2
dtype: int64

In [ ]:
condition = category_21[13:].sum() > 2
final_category = category_21.loc[:, condition].columns.tolist()
final_category

['health_beauty',
 'furniture_decor',
 'auto',
 'watches_gifts',
 'bed_bath_table',
 'computers_accessories',
 'housewares',
 'sports_leisure']

In [ ]:
category_21[13:].sum()

category
health_beauty            16
perfumery                 0
toys                      0
furniture_decor          11
auto                      5
garden_tools              1
telephony                 0
watches_gifts            12
bed_bath_table           13
computers_accessories    12
cool_stuff                2
housewares                7
sports_leisure           12
office_furniture          0
baby                      1
musical_instruments       0
small_appliances          0
stationery                1
dtype: int64

In [ ]:
category_21[final_category][13:]

category,health_beauty,furniture_decor,auto,watches_gifts,bed_bath_table,computers_accessories,housewares,sports_leisure
2018-01,2,2,0,1,2,2,1,2
2018-02,2,1,1,1,2,2,1,2
2018-03,2,2,0,1,2,2,0,2
2018-04,2,2,1,2,2,2,1,2
2018-05,2,1,0,2,1,1,1,1
2018-06,2,1,1,2,2,1,1,1
2018-07,2,1,1,2,1,1,1,1
2018-08,2,1,1,1,1,1,1,1

In [ ]:
top = (category_21[final_category][13:].sum().sort_index())

In [ ]:
z_lst = []
for x, y in zip(ym, report_df_lst):
    z_lst.append(pd.DataFrame({x:y['z_total'].values}, index=y['category']).T)

In [ ]:
z_total = pd.concat(z_lst, axis=0).fillna(0).sort_index()
z_total = z_total[final_category]
z_total[13:].sum().sort_values(ascending=False)

category
bed_bath_table           6.73
computers_accessories    3.99
health_beauty           -0.08
watches_gifts           -0.83
auto                    -1.12
sports_leisure          -1.22
housewares              -1.34
furniture_decor         -2.80
dtype: float64

In [ ]:
display(category_21[final_category][13:])
print('-'*150)
display(z_total[13:])

category,health_beauty,furniture_decor,auto,watches_gifts,bed_bath_table,computers_accessories,housewares,sports_leisure
2018-01,2,2,0,1,2,2,1,2
2018-02,2,1,1,1,2,2,1,2
2018-03,2,2,0,1,2,2,0,2
2018-04,2,2,1,2,2,2,1,2
2018-05,2,1,0,2,1,1,1,1
2018-06,2,1,1,2,2,1,1,1
2018-07,2,1,1,2,1,1,1,1
2018-08,2,1,1,1,1,1,1,1

------------------------------------------------------------------------------------------------------------------------------------------------------

category,health_beauty,furniture_decor,auto,watches_gifts,bed_bath_table,computers_accessories,housewares,sports_leisure
2018-01,0.19,-0.07,0.00,0.65,0.84,1.14,-0.36,0.02
2018-02,-0.02,-0.02,-0.09,0.22,0.25,-0.13,-0.23,0.02
2018-03,-0.26,-0.76,0.00,-0.40,0.66,0.93,0.00,-0.16
2018-04,0.18,-0.34,-0.11,-0.28,1.01,0.80,-0.33,-0.02
2018-05,-0.02,-0.36,0.00,-0.24,1.00,0.16,-0.15,-0.39
2018-06,-0.16,-0.29,-0.30,-0.36,1.08,0.39,-0.13,-0.22
2018-07,-0.11,-0.53,-0.18,-0.10,0.64,0.38,0.03,-0.14
2018-08,0.12,-0.43,-0.44,-0.32,1.25,0.32,-0.17,-0.33

In [ ]:
display(category_21[final_category][13:].sum())
print('-'*30)
display(z_total[13:].sum())

category
health_beauty            16
furniture_decor          11
auto                      5
watches_gifts            12
bed_bath_table           13
computers_accessories    12
housewares                7
sports_leisure           12
dtype: int64

------------------------------

category
health_beauty           -0.08
furniture_decor         -2.80
auto                    -1.12
watches_gifts           -0.83
bed_bath_table           6.73
computers_accessories    3.99
housewares              -1.34
sports_leisure          -1.22
dtype: float64

In [ ]:
top8_cat = np.array(category_21[final_category][13:].sum().index)
top8_cluster = category_21[final_category][13:].sum().values
top8_z_total= z_total[13:].sum().values

In [ ]:
top8_etc = pd.DataFrame({'category':top8_cat, 'cluster':top8_cluster, 'Z_total':top8_z_total})
top8_etc

                category  cluster  Z_total
0          health_beauty       16    -0.08
1        furniture_decor       11    -2.80
2                   auto        5    -1.12
3          watches_gifts       12    -0.83
4         bed_bath_table       13     6.73
5  computers_accessories       12     3.99
6             housewares        7    -1.34
7         sports_leisure       12    -1.22

In [ ]:
top8_rfm = pd.read_csv(raw_path + 'Top8_RFM.csv')
top8_rfm['RFM_total'] = round(top8_rfm['RFM_total'], 2)
top8_rfm = top8_rfm.replace('house_wares', 'housewares')
top8_rfm

                category  RFM_total
0                   auto       0.66
1         bed_bath_table       1.10
2  computers_accessories       0.71
3        furniture_decor       1.05
4          health_beauty       0.43
5             housewares       0.65
6         sports_leisure       0.86
7          watches_gifts       0.76

In [ ]:
top8_evaluation = pd.merge(top8_etc, top8_rfm, on='category').sort_values('category').reset_index(drop=True)
top8_evaluation

                category  cluster  Z_total  RFM_total
0                   auto        5    -1.12       0.66
1         bed_bath_table       13     6.73       1.10
2  computers_accessories       12     3.99       0.71
3        furniture_decor       11    -2.80       1.05
4          health_beauty       16    -0.08       0.43
5             housewares        7    -1.34       0.65
6         sports_leisure       12    -1.22       0.86
7          watches_gifts       12    -0.83       0.76

In [ ]:
print()
print('top8_evaluation ordered by category')
display(top8_evaluation)

print()
print('top8_evaluation ordered by cluster')
display(top8_evaluation.sort_values('cluster'
, ascending=False).reset_index(drop=True))
print()
print('top8_evaluation ordered by Z_total')
display(top8_evaluation.sort_values('Z_total'
, ascending=False).reset_index(drop=True))
print()
print('top8_evaluation ordered by RFM_total')
display(top8_evaluation.sort_values('RFM_total'
, ascending=False).reset_index(drop=True))

top8_evaluation ordered by category

                category  cluster  Z_total  RFM_total
0                   auto        5    -1.12       0.66
1         bed_bath_table       13     6.73       1.10
2  computers_accessories       12     3.99       0.71
3        furniture_decor       11    -2.80       1.05
4          health_beauty       16    -0.08       0.43
5             housewares        7    -1.34       0.65
6         sports_leisure       12    -1.22       0.86
7          watches_gifts       12    -0.83       0.76

top8_evaluation ordered by cluster

                category  cluster  Z_total  RFM_total
0          health_beauty       16    -0.08       0.43
1         bed_bath_table       13     6.73       1.10
2  computers_accessories       12     3.99       0.71
3         sports_leisure       12    -1.22       0.86
4          watches_gifts       12    -0.83       0.76
5        furniture_decor       11    -2.80       1.05
6             housewares        7    -1.34       0.65
7                   auto        5    -1.12       0.66

top8_evaluation ordered by Z_total

                category  cluster  Z_total  RFM_total
0         bed_bath_table       13     6.73       1.10
1  computers_accessories       12     3.99       0.71
2          health_beauty       16    -0.08       0.43
3          watches_gifts       12    -0.83       0.76
4                   auto        5    -1.12       0.66
5         sports_leisure       12    -1.22       0.86
6             housewares        7    -1.34       0.65
7        furniture_decor       11    -2.80       1.05

top8_evaluation ordered by RFM_total

                category  cluster  Z_total  RFM_total
0         bed_bath_table       13     6.73       1.10
1        furniture_decor       11    -2.80       1.05
2         sports_leisure       12    -1.22       0.86
3          watches_gifts       12    -0.83       0.76
4  computers_accessories       12     3.99       0.71
5                   auto        5    -1.12       0.66
6             housewares        7    -1.34       0.65
7          health_beauty       16    -0.08       0.43

In [ ]:
top8_evaluation.sort_values('RFM_total', ascending=False)['category'].values

array(['bed_bath_table', 'furniture_decor', 'sports_leisure',
       'watches_gifts', 'computers_accessories', 'auto', 'housewares',
       'health_beauty'], dtype=object)

In [ ]:
def standardization(df, col):
    m = (df[col].describe()).loc['mean']
    s = (df[col].describe()).loc['std']
    z = (df[col] - m)/s
    return z

In [ ]:
top8_evaluation['Z'] = standardization(top8_evaluation, 'cluster') + standardization(top8_evaluation, 'Z_total') +  standardization(top8_evaluation, 'RFM_total')
top8_evaluation.sort_values('Z', ascending=False).reset_index(drop=True)

                category  cluster  Z_total  RFM_total   score_1         Z
0         bed_bath_table       13     6.73       1.10  3.995518  3.995518
1  computers_accessories       12     3.99       0.71  1.090144  1.090144
2        furniture_decor       11    -2.80       1.05  0.238459  0.238459
3         sports_leisure       12    -1.22       0.86  0.155571  0.155571
4          watches_gifts       12    -0.83       0.76 -0.176821 -0.176821
5          health_beauty       16    -0.08       0.43 -0.285418 -0.285418
6             housewares        7    -1.34       0.65 -2.276800 -2.276800
7                   auto        5    -1.12       0.66 -2.740653 -2.740653

In [ ]:
top8_evaluation['score_2'] = round(standardization(top8_evaluation, 'cluster'), 2) + round(standardization(top8_evaluation, 'Z_total'), 2) +  (top8_evaluation['RFM_total'])
top8_evaluation.sort_values('score_2', ascending=False).reset_index(drop=True)

,category,cluster,Z_total,RFM_total,score_1,Z,score_2
0,bed_bath_table,13,6.73,1.10,3.995518,3.995518,3.64
1,computers_accessories,12,3.99,0.71,1.090144,1.090144,2.11
2,health_beauty,16,-0.08,0.43,-0.285418,-0.285418,1.72
3,watches_gifts,12,-0.83,0.76,-0.176821,-0.176821,0.66
4,sports_leisure,12,-1.22,0.86,0.155571,0.155571,0.64
5,furniture_decor,11,-2.80,1.05,0.238459,0.238459,0.05
6,housewares,7,-1.34,0.65,-2.276800,-2.276800,-1.04
7,auto,5,-1.12,0.66,-2.740653,-2.740653,-1.55